### ISSUE TITLE
Todo next (features)

### ISSUE THREAD

**Issue by AndreMicheletti** [AndreMicheletti/pytest-sorter#1]
- [ ] allow to reset/override the `.test_history` file
- [ ] remove old tests from `.test_history` file (automatically/manually?)
- [x] make it compatible with `pytest-xdist`
- [ ] make documentation
